/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ChildRouteImport } from './routes/child'
import { Route as ClinicianRouteImport } from './routes/clinician'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LumatwinRouteImport } from './routes/lumatwin'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as OnboardingChildRouteImport } from './routes/onboarding.child'
import { Route as OnboardingParentRouteImport } from './routes/onboarding.parent'
import { Route as ReplayResultIdRouteImport } from './routes/replay.$resultId'
import { Route as ReportResultIdRouteImport } from './routes/report.$resultId'
import { Route as ResultsResultIdRouteImport } from './routes/results.$resultId'
import { Route as ScreeningIndexRouteImport } from './routes/screening.index'
import { Route as AssessmentBandIdGuideRouteImport } from './routes/assessment.$bandId.guide'
import { Route as AssessmentBandIdLiveRouteImport } from './routes/assessment.$bandId.live'
import { Route as AssessmentBandIdManualRouteImport } from './routes/assessment.$bandId.manual'
import { Route as AssessmentBandIdProcessingRouteImport } from './routes/assessment.$bandId.processing'
import { Route as AssessmentBandIdRecordRouteImport } from './routes/assessment.$bandId.record'
import { Route as AssessmentBandIdUploadRouteImport } from './routes/assessment.$bandId.upload'
import { Route as ScreeningActivityIdAnalysisRouteImport } from './routes/screening.$activityId.analysis'
import { Route as ScreeningActivityIdSubjectRouteImport } from './routes/screening.$activityId.subject'
import { Route as ScreeningActivityIdUploadRouteImport } from './routes/screening.$activityId.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianRoute = ClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LumatwinRoute = LumatwinRouteImport.update({
  id: '/lumatwin',
  path: '/lumatwin',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingChildRoute = OnboardingChildRouteImport.update({
  id: '/onboarding/child',
  path: '/onboarding/child',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingParentRoute = OnboardingParentRouteImport.update({
  id: '/onboarding/parent',
  path: '/onboarding/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayResultIdRoute = ReplayResultIdRouteImport.update({
  id: '/replay/$resultId',
  path: '/replay/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportResultIdRoute = ReportResultIdRouteImport.update({
  id: '/report/$resultId',
  path: '/report/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsResultIdRoute = ResultsResultIdRouteImport.update({
  id: '/results/$resultId',
  path: '/results/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningIndexRoute = ScreeningIndexRouteImport.update({
  id: '/screening/',
  path: '/screening/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBandIdGuideRoute = AssessmentBandIdGuideRouteImport.update({
  id: '/assessment/$bandId/guide',
  path: '/assessment/$bandId/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBandIdLiveRoute = AssessmentBandIdLiveRouteImport.update({
  id: '/assessment/$bandId/live',
  path: '/assessment/$bandId/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBandIdManualRoute = AssessmentBandIdManualRouteImport.update({
  id: '/assessment/$bandId/manual',
  path: '/assessment/$bandId/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBandIdProcessingRoute =
  AssessmentBandIdProcessingRouteImport.update({
    id: '/assessment/$bandId/processing',
    path: '/assessment/$bandId/processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentBandIdRecordRoute = AssessmentBandIdRecordRouteImport.update({
  id: '/assessment/$bandId/record',
  path: '/assessment/$bandId/record',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBandIdUploadRoute = AssessmentBandIdUploadRouteImport.update({
  id: '/assessment/$bandId/upload',
  path: '/assessment/$bandId/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningActivityIdAnalysisRoute =
  ScreeningActivityIdAnalysisRouteImport.update({
    id: '/screening/$activityId/analysis',
    path: '/screening/$activityId/analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScreeningActivityIdSubjectRoute =
  ScreeningActivityIdSubjectRouteImport.update({
    id: '/screening/$activityId/subject',
    path: '/screening/$activityId/subject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScreeningActivityIdUploadRoute =
  ScreeningActivityIdUploadRouteImport.update({
    id: '/screening/$activityId/upload',
    path: '/screening/$activityId/upload',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/assistant': typeof AssistantRoute
  '/child': typeof ChildRoute
  '/clinician': typeof ClinicianRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/lumatwin': typeof LumatwinRoute
  '/prediction': typeof PredictionRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/child': typeof OnboardingChildRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/replay/$resultId': typeof ReplayResultIdRoute
  '/report/$resultId': typeof ReportResultIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/screening/': typeof ScreeningIndexRoute
  '/assessment/$bandId/guide': typeof AssessmentBandIdGuideRoute
  '/assessment/$bandId/live': typeof AssessmentBandIdLiveRoute
  '/assessment/$bandId/manual': typeof AssessmentBandIdManualRoute
  '/assessment/$bandId/processing': typeof AssessmentBandIdProcessingRoute
  '/assessment/$bandId/record': typeof AssessmentBandIdRecordRoute
  '/assessment/$bandId/upload': typeof AssessmentBandIdUploadRoute
  '/screening/$activityId/analysis': typeof ScreeningActivityIdAnalysisRoute
  '/screening/$activityId/subject': typeof ScreeningActivityIdSubjectRoute
  '/screening/$activityId/upload': typeof ScreeningActivityIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/assistant': typeof AssistantRoute
  '/child': typeof ChildRoute
  '/clinician': typeof ClinicianRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/lumatwin': typeof LumatwinRoute
  '/prediction': typeof PredictionRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/child': typeof OnboardingChildRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/replay/$resultId': typeof ReplayResultIdRoute
  '/report/$resultId': typeof ReportResultIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/screening': typeof ScreeningIndexRoute
  '/assessment/$bandId/guide': typeof AssessmentBandIdGuideRoute
  '/assessment/$bandId/live': typeof AssessmentBandIdLiveRoute
  '/assessment/$bandId/manual': typeof AssessmentBandIdManualRoute
  '/assessment/$bandId/processing': typeof AssessmentBandIdProcessingRoute
  '/assessment/$bandId/record': typeof AssessmentBandIdRecordRoute
  '/assessment/$bandId/upload': typeof AssessmentBandIdUploadRoute
  '/screening/$activityId/analysis': typeof ScreeningActivityIdAnalysisRoute
  '/screening/$activityId/subject': typeof ScreeningActivityIdSubjectRoute
  '/screening/$activityId/upload': typeof ScreeningActivityIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/assistant': typeof AssistantRoute
  '/child': typeof ChildRoute
  '/clinician': typeof ClinicianRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/lumatwin': typeof LumatwinRoute
  '/prediction': typeof PredictionRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/child': typeof OnboardingChildRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/replay/$resultId': typeof ReplayResultIdRoute
  '/report/$resultId': typeof ReportResultIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/screening/': typeof ScreeningIndexRoute
  '/assessment/$bandId/guide': typeof AssessmentBandIdGuideRoute
  '/assessment/$bandId/live': typeof AssessmentBandIdLiveRoute
  '/assessment/$bandId/manual': typeof AssessmentBandIdManualRoute
  '/assessment/$bandId/processing': typeof AssessmentBandIdProcessingRoute
  '/assessment/$bandId/record': typeof AssessmentBandIdRecordRoute
  '/assessment/$bandId/upload': typeof AssessmentBandIdUploadRoute
  '/screening/$activityId/analysis': typeof ScreeningActivityIdAnalysisRoute
  '/screening/$activityId/subject': typeof ScreeningActivityIdSubjectRoute
  '/screening/$activityId/upload': typeof ScreeningActivityIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/assistant'
    | '/child'
    | '/clinician'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/lumatwin'
    | '/prediction'
    | '/progress'
    | '/recommendations'
    | '/api/chat'
    | '/onboarding/child'
    | '/onboarding/parent'
    | '/replay/$resultId'
    | '/report/$resultId'
    | '/results/$resultId'
    | '/screening/'
    | '/assessment/$bandId/guide'
    | '/assessment/$bandId/live'
    | '/assessment/$bandId/manual'
    | '/assessment/$bandId/processing'
    | '/assessment/$bandId/record'
    | '/assessment/$bandId/upload'
    | '/screening/$activityId/analysis'
    | '/screening/$activityId/subject'
    | '/screening/$activityId/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/assistant'
    | '/child'
    | '/clinician'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/lumatwin'
    | '/prediction'
    | '/progress'
    | '/recommendations'
    | '/api/chat'
    | '/onboarding/child'
    | '/onboarding/parent'
    | '/replay/$resultId'
    | '/report/$resultId'
    | '/results/$resultId'
    | '/screening'
    | '/assessment/$bandId/guide'
    | '/assessment/$bandId/live'
    | '/assessment/$bandId/manual'
    | '/assessment/$bandId/processing'
    | '/assessment/$bandId/record'
    | '/assessment/$bandId/upload'
    | '/screening/$activityId/analysis'
    | '/screening/$activityId/subject'
    | '/screening/$activityId/upload'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/assistant'
    | '/child'
    | '/clinician'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/lumatwin'
    | '/prediction'
    | '/progress'
    | '/recommendations'
    | '/api/chat'
    | '/onboarding/child'
    | '/onboarding/parent'
    | '/replay/$resultId'
    | '/report/$resultId'
    | '/results/$resultId'
    | '/screening/'
    | '/assessment/$bandId/guide'
    | '/assessment/$bandId/live'
    | '/assessment/$bandId/manual'
    | '/assessment/$bandId/processing'
    | '/assessment/$bandId/record'
    | '/assessment/$bandId/upload'
    | '/screening/$activityId/analysis'
    | '/screening/$activityId/subject'
    | '/screening/$activityId/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AssistantRoute: typeof AssistantRoute
  ChildRoute: typeof ChildRoute
  ClinicianRoute: typeof ClinicianRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LumatwinRoute: typeof LumatwinRoute
  PredictionRoute: typeof PredictionRoute
  ProgressRoute: typeof ProgressRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ApiChatRoute: typeof ApiChatRoute
  OnboardingChildRoute: typeof OnboardingChildRoute
  OnboardingParentRoute: typeof OnboardingParentRoute
  ReplayResultIdRoute: typeof ReplayResultIdRoute
  ReportResultIdRoute: typeof ReportResultIdRoute
  ResultsResultIdRoute: typeof ResultsResultIdRoute
  ScreeningIndexRoute: typeof ScreeningIndexRoute
  AssessmentBandIdGuideRoute: typeof AssessmentBandIdGuideRoute
  AssessmentBandIdLiveRoute: typeof AssessmentBandIdLiveRoute
  AssessmentBandIdManualRoute: typeof AssessmentBandIdManualRoute
  AssessmentBandIdProcessingRoute: typeof AssessmentBandIdProcessingRoute
  AssessmentBandIdRecordRoute: typeof AssessmentBandIdRecordRoute
  AssessmentBandIdUploadRoute: typeof AssessmentBandIdUploadRoute
  ScreeningActivityIdAnalysisRoute: typeof ScreeningActivityIdAnalysisRoute
  ScreeningActivityIdSubjectRoute: typeof ScreeningActivityIdSubjectRoute
  ScreeningActivityIdUploadRoute: typeof ScreeningActivityIdUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician': {
      id: '/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof ClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumatwin': {
      id: '/lumatwin'
      path: '/lumatwin'
      fullPath: '/lumatwin'
      preLoaderRoute: typeof LumatwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/child': {
      id: '/onboarding/child'
      path: '/onboarding/child'
      fullPath: '/onboarding/child'
      preLoaderRoute: typeof OnboardingChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/parent': {
      id: '/onboarding/parent'
      path: '/onboarding/parent'
      fullPath: '/onboarding/parent'
      preLoaderRoute: typeof OnboardingParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/$resultId': {
      id: '/replay/$resultId'
      path: '/replay/$resultId'
      fullPath: '/replay/$resultId'
      preLoaderRoute: typeof ReplayResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$resultId': {
      id: '/report/$resultId'
      path: '/report/$resultId'
      fullPath: '/report/$resultId'
      preLoaderRoute: typeof ReportResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$resultId': {
      id: '/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof ResultsResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/': {
      id: '/screening/'
      path: '/screening'
      fullPath: '/screening/'
      preLoaderRoute: typeof ScreeningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$bandId/guide': {
      id: '/assessment/$bandId/guide'
      path: '/assessment/$bandId/guide'
      fullPath: '/assessment/$bandId/guide'
      preLoaderRoute: typeof AssessmentBandIdGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$bandId/live': {
      id: '/assessment/$bandId/live'
      path: '/assessment/$bandId/live'
      fullPath: '/assessment/$bandId/live'
      preLoaderRoute: typeof AssessmentBandIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$bandId/manual': {
      id: '/assessment/$bandId/manual'
      path: '/assessment/$bandId/manual'
      fullPath: '/assessment/$bandId/manual'
      preLoaderRoute: typeof AssessmentBandIdManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$bandId/processing': {
      id: '/assessment/$bandId/processing'
      path: '/assessment/$bandId/processing'
      fullPath: '/assessment/$bandId/processing'
      preLoaderRoute: typeof AssessmentBandIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$bandId/record': {
      id: '/assessment/$bandId/record'
      path: '/assessment/$bandId/record'
      fullPath: '/assessment/$bandId/record'
      preLoaderRoute: typeof AssessmentBandIdRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$bandId/upload': {
      id: '/assessment/$bandId/upload'
      path: '/assessment/$bandId/upload'
      fullPath: '/assessment/$bandId/upload'
      preLoaderRoute: typeof AssessmentBandIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/$activityId/analysis': {
      id: '/screening/$activityId/analysis'
      path: '/screening/$activityId/analysis'
      fullPath: '/screening/$activityId/analysis'
      preLoaderRoute: typeof ScreeningActivityIdAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/$activityId/subject': {
      id: '/screening/$activityId/subject'
      path: '/screening/$activityId/subject'
      fullPath: '/screening/$activityId/subject'
      preLoaderRoute: typeof ScreeningActivityIdSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/$activityId/upload': {
      id: '/screening/$activityId/upload'
      path: '/screening/$activityId/upload'
      fullPath: '/screening/$activityId/upload'
      preLoaderRoute: typeof ScreeningActivityIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  AssistantRoute: AssistantRoute,
  ChildRoute: ChildRoute,
  ClinicianRoute: ClinicianRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LumatwinRoute: LumatwinRoute,
  PredictionRoute: PredictionRoute,
  ProgressRoute: ProgressRoute,
  RecommendationsRoute: RecommendationsRoute,
  ApiChatRoute: ApiChatRoute,
  OnboardingChildRoute: OnboardingChildRoute,
  OnboardingParentRoute: OnboardingParentRoute,
  ReplayResultIdRoute: ReplayResultIdRoute,
  ReportResultIdRoute: ReportResultIdRoute,
  ResultsResultIdRoute: ResultsResultIdRoute,
  ScreeningIndexRoute: ScreeningIndexRoute,
  AssessmentBandIdGuideRoute: AssessmentBandIdGuideRoute,
  AssessmentBandIdLiveRoute: AssessmentBandIdLiveRoute,
  AssessmentBandIdManualRoute: AssessmentBandIdManualRoute,
  AssessmentBandIdProcessingRoute: AssessmentBandIdProcessingRoute,
  AssessmentBandIdRecordRoute: AssessmentBandIdRecordRoute,
  AssessmentBandIdUploadRoute: AssessmentBandIdUploadRoute,
  ScreeningActivityIdAnalysisRoute: ScreeningActivityIdAnalysisRoute,
  ScreeningActivityIdSubjectRoute: ScreeningActivityIdSubjectRoute,
  ScreeningActivityIdUploadRoute: ScreeningActivityIdUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
